# Generated by Django 5.1.2 on 2024-11-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityName', models.CharField(max_length=200)),
                ('CourseName', models.CharField(max_length=800)),
                ('content', models.TextField()),
            ],
        ),
    ]
