# Generated by Django 5.1.2 on 2024-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_education_resultdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='extras',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='ResultDate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
