# Generated by Django 5.1.2 on 2024-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_education_extras_alter_education_resultdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(default='', max_length=300)),
                ('JobDate', models.CharField(default='', max_length=400)),
                ('JobResponsibilities', models.TextField()),
                ('TechnologiesUsed', models.TextField()),
            ],
        ),
    ]
