# Generated by Django 5.1.4 on 2024-12-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(default='', max_length=400)),
                ('ProjectDescription', models.TextField()),
                ('TechnologiesUsed', models.TextField()),
            ],
        ),
    ]
