# Generated by Django 5.1.4 on 2024-12-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ProjectImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
