# Generated by Django 5.1.4 on 2024-12-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_projects_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles_certification_accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.URLField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
    ]
